spring:
  application:
    name: 15-SpriongBootRest-TicketBooking
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: nageswara
    password: nageswara
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 9092
